"""chat message seq identity

Revision ID: 938f480f88ec
Revises: 5460308adbb7
Create Date: 2026-09-25 10:24:39.021101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938f480f88ec'
down_revision: Union[str, Sequence[str], None] = '5460308adbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False))
    op.create_index(op.f('ix_chat_messages_seq'), 'chat_messages', ['seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_seq'), table_name='chat_messages')
    op.drop_column('chat_messages', 'seq')
    # ### end Alembic commands ###
