import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.schemas.itinerary import ItineraryResponse


class ChatRequest(BaseModel):
    session_id: uuid.UUID  # generated by the client when a new chat starts
    message: str = Field(min_length=1, max_length=1000)

    @field_validator("message")
    @classmethod
    def _not_blank(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("message must not be blank")
        return v


class ChatResponse(BaseModel):
    session_id: uuid.UUID
    reply_text: str
    conversation_state: str
    extracted_fields: Dict[str, Any] = {}
    next_field: Optional[str] = None
    trip_id: Optional[uuid.UUID] = None
    itinerary: Optional[ItineraryResponse] = None
    actions: List[str] = []


class ChatMessageOut(BaseModel):
    role: str
    content: str
    created_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class ChatHistoryResponse(BaseModel):
    session_id: uuid.UUID
    state: str
    slots: Dict[str, Any] = {}
    next_field: Optional[str] = None
    trip_id: Optional[uuid.UUID] = None
    messages: List[ChatMessageOut] = []
